name: Revision de Sintaxis

on:
  push:
    branches:
      - main
  pull_request: 
    branches: [main]
    types: [opened, synchronize]



jobs:

  install:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.1.0
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm install -no--audit -no--fund

  Avoid_redundance:
    runs-on: ubuntu-latest
    steps:
      - name: Evitando Redundancia
        if: ${{github.event_name == 'push'}}
        uses:  styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{secrets.GITHUB_TOKEN}}
  Build:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.1.0
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm install -no--audit -no--fund
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.1.0
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm install -no--audit -no--fund
      - uses: actions/download-artifact@v4
        with:
          name: dist 
      - name: Test
        run: npm run test

  Deploy:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar secrets
        if: ${{github.event_name == 'push'}}
        run: echo ${{ secrets.HER_GMAIL }}
##     - name: Cypress.io
##        uses: cypress-io/github-action@v2
##        with:
##          command: npm run test:e2e
##          start: npm run start-test
##          wait-on: 'http://localhost:5000'
