name: Revision de Sintaxis

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout            
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          browser: chrome
          wait-on: 'http://localhost:5000'