name: Revision de Sintaxis

on:
  push:
    branches:
      - main
  pull_request: 
    branches: [main]
    types: [opened, synchronize]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Evitando Redundancia
        if: ${{github.event_name == 'push'}}
        uses:  styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{secrets.GITHUB_TOKEN}}
          run: echo "Evitando Redundancia"

      - name: Checkout            
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '14.0'
      - name: Install dependencies
        run: npm install -no--audit -no--fund
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Mostrar secrets
        if: ${{github.event_name == 'push'}}
        run: echo ${{ secrets.HER_GMAIL }}
##     - name: Cypress.io
##        uses: cypress-io/github-action@v2
##        with:
##          command: npm run test:e2e
##          start: npm run start-test
##          wait-on: 'http://localhost:5000'
