name: Revision de Sintaxis

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout            
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional --no-package-lock --no-progress --no-save
      - name: Verificacion con Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      
