name: Revision de Sintaxis

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout            
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Verificacion con Lint
        run: npm run eslint
